### ISSUE TITLE
XPath throws exceptions with namespaced xml tags

### ISSUE THREAD

**Issue by Poly3k** [AngleSharp/AngleSharp.XPath#18]
There seems to be a bug (or lack of compatibility) with namespaced tags like <xhtml:link />. If you search for that tag with XPath (like: //xhtml:link) an exception is thrown.
The xhtml namespace is defined in the xml tag, thus it should be detected. I see no API to add the namespace manually.

Exception:
Unhandled exception. System.Xml.XPath.XPathException: Namespace Manager or XsltContext needed. This query has a prefix, variable, or user-defined function.
   at MS.Internal.Xml.XPath.CompiledXpathExpr.get_QueryTree()
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr, XPathNodeIterator context)
   at System.Xml.XPath.XPathNavigator.Evaluate(XPathExpression expr)
   at System.Xml.XPath.XPathNavigator.Select(XPathExpression expr)
   at AngleSharp.XPath.Extensions.SelectNodes(IElement element, String xpath)
   at Program.Main()

I've made a small example app on Fiddle which you can find here:
https://dotnetfiddle.net/9hDhwH

Best regards,
Stefan

**Comment by denis-ivanov** [comment]
Good day!
I'll see it later.

**Comment by denis-ivanov** [comment]
```csharp
using System;
using AngleSharp.Dom;
using AngleSharp.XPath;
using AngleSharp.Xml.Parser;
					
public class Program
{
	public static string Xml = "<?xml version=\"1.0\" encoding=\"utf-8\" ?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.test.com/de/accounts/profile</loc><xhtml:link rel=\"alternate\" hreflang=\"fr\" href=\"https://www.test.com/fr/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"en\" href=\"https://www.test.com/en/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"it\" href=\"https://www.test.com/it/accounts/profile\" /><changefreq>weekly</changefreq><priority>0.4</priority></url></urlset>";
	
	public static void Main()
	{
		var parser = new XmlParser();
		var doc = parser.ParseDocument(Xml);
		var nodeList = doc.DocumentElement.SelectNodes("//urlset/url/xhtml:link");
		foreach (var entry in nodeList)
			Console.WriteLine(string.Join(",", entry.TextContent));
		
	}
}
```

**Comment by yinyue200** [comment]
I believe the best way to fix is adding SelectNodesNS and SelectSingleNodeNS

**Comment by denis-ivanov** [comment]
Problem solved in AngleSharp.XPath 1.1.6

```csharp
[Test]
public void SelectSingleNode_IgnoreNamespaces_ShouldReturnNode()
{
    // Arrange
    var xml = "<?xml version=\"1.0\" encoding=\"utf-8\" ?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.test.com/de/accounts/profile</loc><xhtml:link rel=\"alternate\" hreflang=\"fr\" href=\"https://www.test.com/fr/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"en\" href=\"https://www.test.com/en/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"it\" href=\"https://www.test.com/it/accounts/profile\" /><changefreq>weekly</changefreq><priority>0.4</priority></url></urlset>";
    var parser = new XmlParser();
    var doc = parser.ParseDocument(xml);

    // Act
    var node = doc.DocumentElement.SelectSingleNode("/urlset/url/link");

    // Assert
    Assert.IsNotNull(node);
    Assert.That(node.NodeName, Is.EqualTo("xhtml:link"));
}

[Test]
public void SelectSingleNode_DontIgnoreNamespaces_ShouldReturnNode()
{
    // Arrange
    var xml = "<?xml version=\"1.0\" encoding=\"utf-8\" ?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\" xmlns:xhtml=\"http://www.w3.org/1999/xhtml\"><url><loc>https://www.test.com/de/accounts/profile</loc><xhtml:link rel=\"alternate\" hreflang=\"fr\" href=\"https://www.test.com/fr/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"en\" href=\"https://www.test.com/en/accounts/profile\" /><xhtml:link rel=\"alternate\" hreflang=\"it\" href=\"https://www.test.com/it/accounts/profile\" /><changefreq>weekly</changefreq><priority>0.4</priority></url></urlset>";
    var parser = new XmlParser();
    var doc = parser.ParseDocument(xml);
    var namespaceManager = new XmlNamespaceManager(new NameTable());

    namespaceManager.AddNamespace("xhtml", "http://www.w3.org/1999/xhtml");
    namespaceManager.AddNamespace("d", "http://www.sitemaps.org/schemas/sitemap/0.9");

    // Act
    var node = doc.DocumentElement.SelectSingleNode("/d:urlset/d:url/xhtml:link", namespaceManager, false);

    // Assert
    Assert.IsNotNull(node);
    Assert.That(node.NodeName, Is.EqualTo("xhtml:link"));
}
```
